"""
Class build to perform CRUD operation on events collection
"""
#import
from app import mongo
from flask import Flask, request
from bson.objectid import ObjectId

# collection
events_coll = mongo.db.events

class Event:
    """
    Class that Creates an instance of event,
    Prepares the data for the database and
    Inserts/Delete/Update the data in the events collection.
    """

    # Create an Event object
    def __init__(self, event_category, event_location, event_age_range,
                event_date, event_time, event_description, _id=None,
                event_created_by=None, event_likes=None,
                event_joined_by=None):
                """
                Initialisation of Event, setting attributes value to None 
                as placeholder for future input. 
                """
                self._id = _id
                self.event_category = event_category
                self.event_location = event_location
                self.event_age_range = event_age_range
                self.event_date = event_date
                self.event_time = event_time
                self.event_description = event_description
                self.event_created_by = event_created_by if not None else 'null'
                self.event_likes = [event_likes] if not None else ['null']
                self.event_joined_by = [event_joined_by] if not None else ['null']

    # method used as a formatter   
    def event_info_to_dic(self):
        """
        Format Event attributes to a dictionary in order to prepare data
        to be inserted to the database.
        """
        event_info = {
            'event_category': self.event_category,
            'event_location': self.event_location,
            'event_age_range': self.event_age_range,
            'event_date': self.event_date,
            'event_time': self.event_time,
            'event_description': self.event_description,
            'event_created_by': self.event_created_by,
            'event_likes': self.event_likes,
            'event_joined_by': self.event_joined_by
        }
        return event_info

    # Add Event to the database
    def insert_event_to_db(self):
        """
        Use event_info dic generated by event_info_to_dic()
        as data to insert into the db.
        """
        try:
            events_coll.insert_one(self.event_info_to_dic())
        except Exception as e:
            print(e)

    # method that use the whole class,
    # can be use on the class without the object instantiated to begin with.
    @classmethod
    def get_all_events(cls):
        """
        Get the events from the db as a list,
        Return a list of Event instances.
        """
        events = list(events_coll.find())
        events_list = []
        if events is not None:
            for event in events:
                one_event = cls(**event)
                events_list.append(one_event)
        return events_list